name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "$KUBE_CONFIG_DATA" | base64 --decode > $HOME/.kube/config

    - name: Update image in deployment
      run: |
        kubectl set image deployment/nginx-demo nginx=nginx:${{ secrets.IMAGE_TAG }}
